---
title: "Lab 3"
author: "Allison Perusse"
date: "2/7/2022"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, load}
library(gapminder)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
view(gapminder)
```

```{r}
gapminder |>
  filter(country %in% c("Italy","Taiwan", "Sweden") & year == 1970-1979)

```
  
```{r}
gapminder |>
   filter(country %in% c("Italy", "Taiwan", "Sweden") & year == 1970-1979) |> 
  select(country, gdpPercap) |>
  print()
```

```{r}
new_gap <- gapminder |> 
  arrange(year) |>
   group_by(country) |>
   mutate(lifeExp_change = lifeExp - lag(lifeExp)) |>
  filter(lifeExp_change < 0) |>
  ungroup() |>
  filter(lifeExp_change == min(lifeExp_change))
 print(new_gap)
 
```

```{r}
gapminder |>
  group_by(country)|>
  summarize(max = max(gdpPercap))
```

```{r}
gapminder |>
  filter(country =="Canada")|>
  ggplot()+
  aes(x = lifeExp, y = gdpPercap)+
  geom_point(alpha = 0.1)+
  scale_x_continuous("Life expectancy") +
  scale_y_continuous(name = "GDP per capita",
                     trans = "log10",
                     labels = scales::dollar_format())+
  labs(title = "Canada's Life Expectancy vs. GDP per Capita")
```

```{r}
library(palmerpenguins)

palmerpenguins::penguins|>
  summarize(mean_billlength = mean(bill_length_mm, na.rm = TRUE),
            sd_billlength = sd(bill_length_mm, na.rm = TRUE),
            mean_flipperlength = mean(flipper_length_mm, na.rm = TRUE),
            sd_flipperlength = sd(flipper_length_mm, na.rm = TRUE))
```

```{r}
ggplot(palmerpenguins::penguins)+
  aes(x = bill_length_mm, y = flipper_length_mm)+
  geom_point(color = "green")+
  scale_x_continuous(name = "Bill Length") +
  scale_y_continuous("Flipper Length")+
  labs(title = "Bill Length by Flipper Length")
```

```{r}
ggplot(na.omit(palmerpenguins::penguins)) +
  aes(y = species, 
      x = body_mass_g,
      fill = species,
      color = species) +
  geom_jitter(height = .15) +
  geom_boxplot(color = "black",
               alpha = .5,
               width = .1,
               size = .5) +
  ggdist::stat_slab(height = .3,
                    color = "black",
                    size = .2,
                    alpha = .5,
                    position = position_nudge(y = .2)) +
  scale_x_continuous("Body Mass") +
  scale_y_discrete("Species") +
  labs(title = "Body Mass by Species")
```