---
title: "Lab 3"
author: "Allison Perusse"
date: "2/7/2022"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, load}
library(gapminder)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
view(gapminder)
```

1.1
```{r}
gapminder |>
  filter(country %in% c("Italy","Taiwan", "Sweden") & year == 1970-1979)

```

1.2
```{r}
gapminder |>
   filter(country %in% c("Italy", "Taiwan", "Sweden") & year == 1970-1979) |> 
  select(country, gdpPercap) |>
  print()
```

1.3
```{r}
new_gap <- gapminder |> 
  arrange(year) |>
   group_by(country) |>
   mutate(lifeExp_change = lifeExp - lag(lifeExp)) |>
  filter(lifeExp_change < 0) |>
  ungroup() |>
  filter(lifeExp_change == min(lifeExp_change))
 print(new_gap)
 
```

1.4
```{r}
gapminder |>
  group_by(country)|>
  summarize(max = max(gdpPercap))
```

1.5
```{r}
gapminder |>
  filter(country %in% "Canada")|>
  ggplot() + 
  aes(x = gdpPercap, y = lifeExp) + 
  geom_point() +
  scale_size_continuous(name = "title", range = c(4, 8)) +
    scale_color_continuous(name = "title", aesthetics = c("color", "fill")) +
  scale_shape_discrete(name = "title")
  scale_x_log10()
```

Exercise 2

2.1
```{r}
gapminder |>
  summarize( mean = mean(lifeExp),
             sd = sd(lifeExp), 
             range = range(lifeExp))
```

```{r}
gapminder |> 
  summarize(mean = mean(gdpPercap),
            sd = sd(gdpPercap), 
            range = range(gdpPercap))
```

```{r}
gapminder |>
  ggplot(
    aes(x = gdpPercap, y = lifeExp, color = continent)) +
  geom_point(alpha = .5)
  )
           
```

2.2

```{r}
gapminder |>
  group_by(continent) |>
  summarize(mean = mean(lifeExp),
             sd = sd(lifeExp), 
             range = range(lifeExp),
            n = n())
```

```{r, plot of lifeExp by cont}
gapminder |>
  ggplot(aes(x = continent, y = lifeExp, fill = continent, color = continent)) +
  geom_jitter(height = .5,
              width = .5,
              alpha = .3)
```

```{r, add boxplot}
gapminder |>
  ggplot(aes(x = continent, y = lifeExp, fill = continent, color = continent)) +
  geom_jitter(height = .5,
              width = .5,
              alpha = .3) +
  geom_boxplot(color = "black", 
               alpha = .1)
```


```{r, raincloud plot}
gapminder |>
  ggplot(aes(x = continent, y = lifeExp, fill = continent, color = continent)) +
  geom_jitter(height = .5,
              width = .5,
              alpha = .3) +
  geom_boxplot(color = "black", 
               alpha = .5, 
               width = .5, 
               size = .5) +
  ggdist::stat_slab(height = .3, 
                    color = "black", 
                    size = .2,
                    alpha = .5,
                    position = position_nudge(y = .1))
```

  