---
title: "Tibble Joins"
author: "Allison Perusse"
date: "2/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
```

```{r}
songs <- read_csv("https://raw.githubusercontent.com/bwiernik/progdata-class/master/data/singer/songs.csv")
locations <- read_csv("https://raw.githubusercontent.com/bwiernik/progdata-class/master/data/singer/loc.csv")

(time <- as_tibble(songs) |> 
   rename(song = title))

(album <- as_tibble(locations) |> 
   select(title, everything()) |> 
   rename(album = release,
          song  = title))
```

1. 
```{r. corresponding album to song}
time |>
 left_join(album, by = "song")

time |> 
  left_join(album, by = c("artist_name", "song"))
```

2. 
```{r. preserving rows}

time |>
  full_join(album, by = c("artist_name", "song"))
```

3.
```{r, year no album}
time |>
  anti_join(album, by = "song")
```

4. 
```{r, artists in time, not album}
time |>
  anti_join(album, by = "artist_name")
```

5.
```{r, all available}
time |>
  full_join(album, by = c("song"))
```

Exercise 2
```{r}
fell <- read_csv("https://raw.githubusercontent.com/jennybc/lotr-tidy/master/data/The_Fellowship_Of_The_Ring.csv")
ttow <- read_csv("https://raw.githubusercontent.com/jennybc/lotr-tidy/master/data/The_Two_Towers.csv")
retk <- read_csv("https://raw.githubusercontent.com/jennybc/lotr-tidy/master/data/The_Return_Of_The_King.csv")
```

1.
```{r}
bind_rows(fell, ttow, retk)
bind_cols(fell,ttow, retk)
```

2.
```{r}
fell |>
  anti_join(ttow, by = "Race") |>
  anti_join(retk, by = "Race")
```

Exercise 3.
```{r}
y <- tibble(x1 = LETTERS[1:3], x2 =  1:3)
z <- tibble(x1 = c("B", "C", "D"), x2 = 2:4)
```

1.
```{r}
intersect(y, z)
```

2.
```{r}
union(
  mutate(y, day = "Day 1"), 
  mutate(z, day = "Day 2")
)
```

3.
```{r}
setdiff(y, z)
```

